### ISSUE TITLE
uncovered case for simple program

### ISSUE THREAD

**Issue by aubertc** [statycc/pymwp#10]
The current example we are using in the notes,

```
int main(){
    int X1;
    int X2;
    X1 + X2;
}
```

produces:

```
In compute_rel
uncovered case ! Create empty RelationList (function call) ?
Decl: X1, [], [], []
  TypeDecl: X1, []
    IdentifierType: ['int']
In compute_rel
uncovered case ! Create empty RelationList (function call) ?
Decl: X2, [], [], []
  TypeDecl: X2, []
    IdentifierType: ['int']
In compute_rel
uncovered case ! Create empty RelationList (function call) ?
BinaryOp: +
  ID: X1
  ID: X2
--- Affiche <relation_list.RelationList object at 0x7f3e314adf98> ---
1:

--- FIN ---
[[]]
```

It seems like valid C code to me and should be analyzed by our program. Am I missing something?

**Comment by aubertc** [comment]
If you compare with https://github.com/seiller/pymwp/blob/master/c_files/basics/assign_expression.c (which is pretty much the same program, but without the assignment), then you can see that it can be compiled and parsed (and executed). So I guess this program should be "valid" under both criteria.

Binary operators should be treated regardless of if they are followed by an assignment, I believe, following the E3 / E4 rules.

**Comment by nkrusch** [comment]
OK. I think if we remove the condition `if ... Assignment` then it should fix this. I will try it.

**Comment by nkrusch** [comment]
Analyzing this example currently after recent changes, it should be written as

```c
int foo(int X1, int X2){
    X1 + X2;
}
```

produces result of empty list of choices: `[]` and matrix:

```
X1  |  +m  +o
X2  |  +o  +m
```

This result is obtained from parameter list alone; the line with `X1+X2` is ignored.

From the paper E3/E4 for e_1 + e_2 gives vector `[ p, m ]` or `[ m, p ]`. How do we compose this vector with the matrix? we need assignment to apply rule A. As of now we still have "uncovered case".

**Comment by aubertc** [comment]
I believe we can close this issue and leave this program in this state: the analysis will, indeed, only produce vectors in this case, not matrices, and if the value is not assigned there is nothing we can say about it.

We can, if we want, raise some flag / error message saying "well, all we have is vectors here", but I don't think this is very useful. 

To answer my original question:

> It seems like valid C code to me and should be analyzed by our program. Am I missing something?

What I was missing is that, from the analysis' perspective, this is only a vector and not something "meaningful".
I guess we can justify this choice practically by noting that if there is no assignment whatsoever in your program, it is a meaningless program in our restricted syntax.

@nkrusch , I will let you close this issue if my answer makes sense.

**Comment by seiller** [comment]
If the code is really this one then the analysis is correct. The values of input variables when the program is ended are the same as those when it started. If you want to use the rules from the paper you need the sum to be assigned to one of the variables.
