### ISSUE TITLE
delta_iter

### ISSUE THREAD

**Issue by nkrusch** [statycc/pymwp#52]
`delta_iter` branch has custom version of Python standard lib `itertools.product` that is used to [generate choices for eval](https://github.com/statycc/pymwp/blob/058a0faa459be6901803ddb7db2e0abd5ec833d9/pymwp/relation.py#L344).

TODO:

- [x] debug delta_iter to [make sure it works correctly](https://github.com/statycc/pymwp/blob/delta_iter/pymwp/delta_iter.py#L5)
- [x] [add unit tests to show the above](https://github.com/statycc/pymwp/blob/delta_iter/tests/test_delta_iter.py)
- [ ] there may be cases where standard lib `itertools.product` is more optimal, in which case should use it over delta_iter
- [x] [update](https://github.com/statycc/pymwp/blob/delta_iter/pymwp/relation.py#L346) `relation.py` to use `delta_iter` implementation

**Comment by ThomasRuby** [comment]
Yes in fact I think at least itertool is more efficient when delta-graph is empty. And surely also when the elements in delta-graphs are too specific (monomials too long). We could compare efficiency regarding to size of monomials.

**Comment by nkrusch** [comment]
If we can capture these edge cases in a conditional then we can choose the implementation based on that condition. The first one should be simple if there is some way to check dg == empty?

**Comment by seiller** [comment]
In principle itertool should work in the exact same way. So if it is faster, it comes from the implementation. I would suggest looking at how things are implemented there and mimicking what they do in our package. This way we get faster for all cases.

**Comment by nkrusch** [comment]
from [Python docs](https://docs.python.org/3/library/itertools.html#itertools.product):

> This function is roughly equivalent to the following code, except that the actual implementation does not build up intermediate results in memory:

```Python
def product(*args, repeat=1):
    # product('ABCD', 'xy') --> Ax Ay Bx By Cx Cy Dx Dy
    # product(range(2), repeat=3) --> 000 001 010 011 100 101 110 111
    pools = [tuple(pool) for pool in args] * repeat
    result = [[]]
    for pool in pools:
        result = [x+[y] for x in result for y in pool]
    for prod in result:
        yield tuple(prod)
```        

Looking at Python source on github [it maybe written in C](https://github.com/python/cpython/blob/f64de53ff01e734d48d1d42195443d7d1646f220/Modules/itertoolsmodule.c)?

**Comment by seiller** [comment]
Hi. I've committed a new version of delta_iter to correct the issues I found in my previous code (see the commit message for details). I think it works correctly but some tests are failing now (I do not have time to check, but 3 out of 4 can probably be easily corrected -- the problem comes from the change of output type in some of the functions). I ran not-infinite examples 7 and 8 and it seems a number of valuations are skipped; these may be good tests subject for a comparison between this version of the code and the main branch (talking about running time here).

**Comment by ThomasRuby** [comment]
> Hi. I've committed a new version of delta_iter to correct the issues I found in my previous code (see the commit message for details). I think it works correctly but some tests are failing now (I do not have time to check, but 3 out of 4 can probably be easily corrected -- the problem comes from the change of output type in some of the functions). I ran not-infinite examples 7 and 8 and it seems a number of valuations are skipped; these may be good tests subject for a comparison between this version of the code and the main branch (talking about running time here).

Done here : https://github.com/statycc/pymwp/commit/5617b33875d755ec0978b177abfababcc209c6bc

I see no relevant diff in running time with theses examples (7 and 8) I think we need more complex examples to see real diff. Or maybe running them several times ?
